apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: 223438050602.dkr.ecr..${AWS_REGION}.amazonaws.com/tetris_images:latest
        ports:
        - containerPort: 8080
